// Données détaillées pour la page de documentation des badges Eza
export const BADGE_DOC_DATA = {
  verified: {
    label: 'Vérifié',
    category: 'Statuts principaux',
    color: 'text-sky-400',
    price: '5€ / mois',
    description: "Le badge Vérifié atteste que l'identité de l'utilisateur a été confirmée par l'équipe Eza. Il garantit qu'il s'agit d'une personne réelle et non d'un compte frauduleux ou usurpé. C'est le badge de base du système de confiance Eza.",
    criteria: [
      "Fournir son nom complet réel et sa date de naissance",
      "Indiquer sa ville de résidence et un numéro de téléphone (optionnel)",
      "Lier au moins un réseau social public actif",
      "Décrire son activité et la raison de la demande",
      "Réponse de l'équipe sous 5 jours ouvrables",
    ],
    perks: [
      "Coche de vérification bleue sur le profil",
      "Identité confirmée publiquement",
      "Réponses boostées dans le feed",
      "Badge animé Vérifié",
    ],
  },
  pro: {
    label: 'Pro',
    category: 'Statuts principaux',
    color: 'text-emerald-400',
    price: '10€ / mois',
    description: "Le badge Pro atteste que l'utilisateur exerce une activité professionnelle. Il est destiné aux créateurs, artistes, entrepreneurs et professionnels qui souhaitent démontrer leur statut professionnel auprès de la communauté Eza.",
    criteria: [
      "Fournir son nom commercial ou structure professionnelle",
      "Indiquer son secteur d'activité et sa ville d'exercice",
      "Fournir un SIRET si applicable",
      "Indiquer depuis quelle année l'activité est en cours",
      "Lier un portfolio ou une chaîne principale",
      "Décrire son audience et ses spécialités",
    ],
    perks: [
      "Coche Pro verte sur le profil",
      "Profil professionnel mis en avant",
      "Statistiques avancées",
      "Badge Pro animé",
    ],
  },
  certified: {
    label: 'Certifié',
    category: 'Statuts principaux',
    color: 'text-amber-400',
    price: '20€ / mois',
    description: "Le badge Certifié est décerné aux utilisateurs dont l'expertise est reconnue et possèdent des références solides. Il s'adresse aux professionnels établis, experts reconnus et créateurs influents qui ont prouvé leur crédibilité à travers un parcours professionnel ou des collaborations notables.",
    criteria: [
      "Démontrer un domaine d'expertise clair et établi",
      "Justifier d'années d'expérience significatives",
      "Avoir une audience ou clientèle conséquente",
      "Posséder des plateformes actives et un portfolio",
      "Fournir des références de collaborations notables",
      "Mentionner distinctions ou prix éventuels",
    ],
    perks: [
      "Coche Certifiée dorée sur le profil",
      "Expertise validée par l'équipe Eza",
      "Priorité absolue dans les recherches",
      "Badge Certifié premium animé",
    ],
  },
  official: {
    label: 'Officiel',
    category: 'Statuts principaux',
    color: 'text-purple-400',
    price: '40€ / mois',
    description: "Le badge Officiel est réservé aux entités, marques, entreprises et organisations légalement reconnues. Il atteste que le compte représente une entité officielle dûment enregistrée et vérifiable dans les registres publics. C'est le plus haut niveau de statut commercial sur Eza.",
    criteria: [
      "Fournir le nom légal exact de l'entité",
      "Indiquer le type d'entité (SA, SAS, Association, Marque...)",
      "Fournir un numéro SIRET, RNA ou d'enregistrement",
      "Disposer d'un site web officiel",
      "Fournir un lien vers une preuve légale (Kbis, Journal Officiel)",
      "Indiquer le rôle du demandeur et un email professionnel",
    ],
    perks: [
      "Coche Officielle violette sur le profil",
      "Entité reconnue et vérifiable légalement",
      "Support prioritaire dédié 24h",
      "Badge Officiel exclusif animé",
    ],
  },
  supreme: {
    label: 'Suprême',
    category: 'Statuts principaux',
    color: 'text-yellow-300',
    price: 'Sur invitation',
    description: "Le badge Suprême est la distinction la plus rare de la plateforme Eza. Il n'est attribué que sur invitation, aux membres les plus reconnus et exceptionnels de la communauté. Ce badge ne s'obtient pas par une démarche, mais par une reconnaissance par l'équipe Eza du parcours, de l'impact et de l'influence exceptionnels d'un membre.",
    criteria: [
      "Attribution exclusive sur invitation par l'équipe Eza",
      "Reconnaissance exceptionnelle au sein de la communauté",
      "Parcours et impact remarquables démontrés",
      "Ne s'obtient pas par une demande directe",
    ],
    perks: [
      "Badge Suprême doré exclusif et animé",
      "Visibilité maximale dans tous les espaces",
      "Accès à des fonctionnalités réservées",
      "Reconnaissance publique en tant que membre d'exception",
    ],
  },
  government: {
    label: 'Gouvernement et multilatéral',
    category: 'Statuts principaux',
    color: 'text-zinc-300',
    price: 'Sur vérification',
    description: "Le badge Gouvernement est attribué aux comptes représentant des institutions gouvernementales, services publics ou entités multilatérales officielles. Il garantit l'authenticité d'un compte parlant au nom d'une autorité publique reconnue.",
    criteria: [
      "Représenter une institution gouvernementale ou multilatérale officielle",
      "Vérification renforcée de l'authenticité institutionnelle",
      "Attribution par l'équipe Eza après contrôle",
    ],
    perks: [
      "Coche Gouvernement grise sur le profil",
      "Authenticité institutionnelle garantie",
      "Visibilité prioritaire",
    ],
  },
  urgency: {
    label: 'Urgence',
    category: 'Rôles système',
    color: 'text-red-400',
    price: '15€ / mois',
    description: "Le badge Urgence est attribué aux professionnels habilités à intervenir sur le terrain en urgence. Il identifie les personnes capables de répondre rapidement à des situations critiques ou des demandes de service urgentes dans leur domaine de compétence.",
    criteria: [
      "Être professionnel habilité aux interventions urgentes",
      "Démontrer sa capacité d'intervention rapide sur le terrain",
      "Validation par l'équipe Eza",
    ],
    perks: [
      "Coche Urgence rouge sur le profil",
      "Identification comme intervenant d'urgence",
      "Visibilité prioritaire en cas de besoin",
    ],
  },
  moderator: {
    label: 'Modérateur',
    category: 'Rôles & Staff',
    color: 'text-red-500',
    price: '—',
    description: "Le badge Modérateur identifie les membres de l'équipe chargés de réguler les discussions, traiter les signalements et faire respecter les règles de la communauté Eza. Ils jouent un rôle clé dans le maintien d'un environnement sain et respectueux.",
    criteria: [
      "Attribution par l'équipe Eza",
      "Engagement actif dans la modération",
      "Connaissance des règles et procédures de la communauté",
    ],
    perks: [
      "Accès aux outils de modération",
      "Badge Modérateur rouge sur le profil",
      "Pouvoir de régulation des discussions et signalements",
    ],
  },
  beta: {
    label: 'Beta Testeur',
    category: 'Engagement',
    color: 'text-rose-400',
    price: '—',
    description: "Le badge Beta Testeur récompense les pionniers qui participent activement aux tests des nouvelles fonctionnalités Eza avant leur lancement public. Ces membres contribuent à améliorer la plateforme par leurs retours d'expérience précieux.",
    criteria: [
      "Participation active aux phases de test bêta",
      "Fournir des retours constructifs et détaillés",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Accès anticipé aux nouvelles fonctionnalités",
      "Badge Beta Testeur rose sur le profil",
      "Canal de feedback direct avec l'équipe",
    ],
  },
  donor: {
    label: 'Donateur',
    category: 'Engagement',
    color: 'text-red-300',
    price: '—',
    description: "Le badge Donateur est attribué aux membres qui soutiennent financièrement la plateforme Eza par des dons. Il reconnaît l'engagement bénévole envers le projet et la communauté, et encourage la pérennité du service.",
    criteria: [
      "Réaliser un don à Eza via la page dédiée",
      "Attribution automatique après confirmation du don",
    ],
    perks: [
      "Badge Donateur sur le profil",
      "Reconnaissance de votre soutien financier",
      "Visibilité dans la liste des donateurs",
    ],
  },
  ambassador: {
    label: 'Ambassadeur',
    category: 'Engagement',
    color: 'text-orange-400',
    price: '25€ / mois',
    description: "Le badge Ambassadeur est décerné aux représentants officiels de marques partenaires Eza. Ces utilisateurs promeuvent activement la plateforme et les produits de leur marque, jouant un rôle de pont entre Eza et leur communauté commerciale.",
    criteria: [
      "Représenter une marque partenaire d'Eza",
      "Démontrer une activité promotionnelle active",
      "Validation par l'équipe Eza et la marque partenaire",
    ],
    perks: [
      "Coche Ambassadeur orange sur le profil",
      "Mise en avant dans les espaces partenaires",
      "Outils de suivi des campagnes promotionnelles",
      "Accès aux événements exclusifs partenaires",
    ],
  },
  developer: {
    label: 'Développeur',
    category: 'Rôles & Staff',
    color: 'text-blue-400',
    price: '—',
    description: "Le badge Développeur identifie les contributeurs au code source d'Eza. Ces membres participent activement au développement technique de la plateforme, que ce soit par des pull requests, des corrections de bugs ou de nouvelles fonctionnalités.",
    criteria: [
      "Contribuer activement au code source d'Eza",
      "Pull requests acceptées et fusionnées",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Développeur bleu sur le profil",
      "Accès au canal de développement",
      "Reconnaissance de contribution technique",
    ],
  },
  translator: {
    label: 'Traducteur',
    category: 'Rôles & Staff',
    color: 'text-cyan-400',
    price: '—',
    description: "Le badge Traducteur récompense les bénévoles qui traduisent la plateforme Eza dans d'autres langues. Leur travail permet à un plus grand nombre d'utilisateurs de profiter d'Eza dans leur langue maternelle, élargissant l'accessibilité de la plateforme.",
    criteria: [
      "Traduire activement l'interface et le contenu d'Eza",
      "Maintenir une qualité de traduction cohérente",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Traducteur cyan sur le profil",
      "Accès aux outils de traduction",
      "Reconnaissance de contribution bénévole",
    ],
  },
  mentor: {
    label: 'Mentor',
    category: 'Rôles & Staff',
    color: 'text-purple-500',
    price: '—',
    description: "Le badge Mentor est attribué aux membres expérimentés qui accompagnent les nouveaux venus dans la communauté Eza. Ils guident les nouveaux utilisateurs dans leur parcours d'apprentissage et les aident à tirer le meilleur parti de la plateforme.",
    criteria: [
      "Démontrer une expérience et une expertise communautaire",
      "S'engager à accompagner activement les nouveaux membres",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Mentor violet sur le profil",
      "Mise en avant comme mentor disponible",
      "Outils de suivi des membres accompagnés",
    ],
  },
  scholar: {
    label: 'Érudit',
    category: 'Engagement',
    color: 'text-indigo-400',
    price: '30€ / mois',
    description: "Le badge Érudit reconnaît les membres faisant preuve de connaissances approfondies et d'un travail de recherche de qualité. Il s'adresse aux experts, chercheurs et spécialistes qui contribuent par leur savoir à enrichir les discussions et le contenu de la communauté.",
    criteria: [
      "Démontrer des connaissances approfondies dans son domaine",
      "Avoir un travail de recherche ou d'analyse reconnu",
      "Contribuer régulièrement par un contenu de qualité",
      "Validation par l'équipe Eza",
    ],
    perks: [
      "Coche Érudit indigo sur le profil",
      "Mise en avant dans les discussions spécialisées",
      "Accès aux espaces de recherche communautaire",
      "Badge Érudit animé",
    ],
  },
  pioneer: {
    label: 'Pionnier',
    category: 'Engagement',
    color: 'text-emerald-500',
    price: '—',
    description: "Le badge Pionnier honore les premiers membres ayant rejoint Eza dès son lancement. Ces utilisateurs ont accompagné la plateforme depuis ses tout débuts et représentent la communauté historique et fondatrice d'Eza.",
    criteria: [
      "Avoir rejoint Eza durant la phase de lancement",
      "Attribution automatique selon la date d'inscription",
    ],
    perks: [
      "Badge Pionnier vert sur le profil",
      "Reconnaissance en tant que membre historique",
      "Accès aux événements de pionniers",
    ],
  },
  advocate: {
    label: 'Avocat',
    category: 'Engagement',
    color: 'text-pink-400',
    price: '—',
    description: "Le badge Avocat est attribué aux militants actifs qui défendent les valeurs de la communauté Eza. Ces membres s'engagent à promouvoir les principes de la plateforme, à soutenir les causes qui leur tiennent à cœur et à encourager d'autres membres à faire de même.",
    criteria: [
      "Démontrer un engagement militant actif",
      "Soutenir et promouvoir les valeurs d'Eza",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Avocat rose sur le profil",
      "Mise en avant dans les espaces de débat",
      "Reconnaissance de votre engagement civique",
    ],
  },
  organizer: {
    label: 'Organisateur',
    category: 'Rôles & Staff',
    color: 'text-teal-400',
    price: '—',
    description: "Le badge Organisateur reconnaît les membres qui organisent régulièrement des événements et des rencontres au sein de la communauté Eza. Ils animent la vie sociale de la plateforme en proposant des rassemblements, des ateliers et des temps forts.",
    criteria: [
      "Organiser activement des événements communautaires",
      "Démontrer une régularité dans l'animation",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Organisateur teal sur le profil",
      "Outils de gestion d'événements",
      "Mise en avant des événements organisés",
    ],
  },
  contributor: {
    label: 'Contributeur',
    category: 'Soutien',
    color: 'text-violet-400',
    price: '—',
    description: "Le badge Contributeur est attribué aux membres qui contribuent régulièrement aux projets, discussions et initiatives de la communauté Eza. Il récompense l'engagement constant et la participation active au-delà de la simple consommation de contenu.",
    criteria: [
      "Contribuer régulièrement aux projets communautaires",
      "Participer activement aux discussions et initiatives",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Contributeur violet sur le profil",
      "Reconnaissance de votre contribution active",
      "Accès aux projets communautaires",
    ],
  },
  early_supporter: {
    label: 'Soutien historique',
    category: 'Soutien',
    color: 'text-amber-500',
    price: '—',
    description: "Le badge Soutien historique honore les membres qui ont soutenu Eza dès les tout débuts du projet, avant même son lancement public. Ces pionniers ont accompagné le projet dans sa phase de construction et ont contribué à son essor.",
    criteria: [
      "Avoir soutenu le projet Eza avant son lancement public",
      "Attribution automatique selon la date de soutien",
    ],
    perks: [
      "Badge Soutien historique ambré sur le profil",
      "Reconnaissance de votre engagement précoce",
      "Accès aux souvenirs et archives du projet",
    ],
  },
  protector: {
    label: 'Protecteur',
    category: 'Rôles & Staff',
    color: 'text-slate-400',
    price: '—',
    description: "Le badge Protecteur identifie les membres qui veillent à la sécurité et au respect des règles dans la communauté Eza. Ils jouent un rôle de sentinelle, aidant à préserver un environnement sain et à protéger les membres contre les abus.",
    criteria: [
      "S'engager activement dans la protection de la communauté",
      "Signaler les abus et comportements nuisibles",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Protecteur gris sur le profil",
      "Accès aux outils de signalement avancés",
      "Reconnaissance de votre rôle de sentinelle",
    ],
  },
  innovator: {
    label: 'Innovateur',
    category: 'Soutien',
    color: 'text-fuchsia-400',
    price: '—',
    description: "Le badge Innovateur récompense les membres qui proposent régulièrement des idées novantes et des fonctionnalités originales pour améliorer Eza. Ces utilisateurs stimulent l'évolution de la plateforme par leur créativité et leur vision前瞻iste.",
    criteria: [
      "Proposer régulièrement des idées et fonctionnalités novatrices",
      "Démontrer une contribution créative continue",
      "Attribution par l'équipe Eza",
    ],
    perks: [
      "Badge Innovateur fuchsia sur le profil",
      "Accès au canal des idées et suggestions",
      "Reconnaissance de votre apport innovant",
    ],
  },
};

export const BADGE_DOC_CATEGORIES = [
  {
    title: 'Statuts principaux',
    description: "Les badges de statut les plus prestigieux, attribués par vérification d'identité ou activité professionnelle.",
    badges: ['verified', 'pro', 'certified', 'official', 'supreme', 'government'],
  },
  {
    title: 'Rôles & Staff',
    description: "Badges attribués aux membres de l'équipe et aux modérateurs de la communauté.",
    badges: ['moderator', 'developer', 'translator', 'mentor', 'organizer', 'protector'],
  },
  {
    title: 'Engagement',
    description: "Badges récompensant l'engagement actif et le soutien à la plateforme.",
    badges: ['beta', 'donor', 'ambassador', 'scholar', 'pioneer', 'advocate'],
  },
  {
    title: 'Soutien',
    description: "Badges reconnaissant les contributions régulières et l'innovation.",
    badges: ['contributor', 'early_supporter', 'innovator'],
  },
  {
    title: 'Rôles système',
    description: "Badges internes attribués aux fondateurs, administrateurs et pilotes.",
    badges: ['urgency'],
  },
];