// Contenu de la documentation publique EZA.
// Chaque sujet = une page dédiée (/documentation/:slug) avec plusieurs sections riches.

export const DOC_TOPICS = [
  {
    slug: 'overview',
    icon: 'Book',
    title: "Vue d'ensemble",
    tagline: "La plateforme EZA en un coup d'œil",
    color: '#38aadc',
    intro: "EZA est une plateforme communautaire et sociale, installable en PWA sur iOS et Android depuis le même code. Elle réunit un réseau social, une messagerie, un forum, un portfolio, un blog, des certifications, des affiliations et des donations dans une seule application responsive et rapide.",
    sections: [
      {
        title: "Les grands pôles",
        body: "L'application est organisée autour de plusieurs pôles qui partagent la même identité, le même système de design et les mêmes utilisateurs. Chaque pôle a sa propre page et ses propres interactions, mais tout est interconnecté : un auteur de publication est aussi un utilisateur avec un profil public, des badges et des affiliations.",
        bullets: [
          "Réseau social — publications, médias, sondages, likes, réponses, mentions, hashtags, suivi d'utilisateurs.",
          "Messagerie — conversations 1-à-1, demandes de contact, modération, messages officiels.",
          "Forum — discussions thématiques, réponses, likes, annonces, épinglage.",
          "Portfolio — galerie de projets, comparaisons avant/après, avis clients.",
          "Blog — articles d'actualité, de conseils, techniques, projets et formation.",
          "Certifications — questionnaire + paiement, badges de vérification.",
          "Affiliations & Écosystème — rattachement d'utilisateurs à des organisations.",
          "Business Space — espace dédié aux comptes organisation.",
          "Donations — soutien financier via Stripe.",
          "Notifications — in-app, push web, email.",
        ],
      },
      {
        title: "Pour qui ?",
        body: "EZA s'adresse à une communauté de créateurs, de pilotes et de clients. Les créateurs partagent leurs réalisations, les clients découvrent un portfolio et demandent des devis, et la communauté échange via le forum et la messagerie. Les organisations peuvent s'affilier et afficher leur logo sur les profils.",
        bullets: [
          "Créateurs et auteurs de contenu (publications, portfolio, blog).",
          "Clients à la recherche de prestations (portfolio, devis, rendez-vous).",
          "Communauté souhaitant échanger (forum, messagerie, social).",
          "Organisations souhaitant exister et recruter des affiliés.",
        ],
      },
      {
        title: "Principes de conception",
        body: "L'application est pensée comme une application native : rapide, tactile, avec un design sombre « Sky » par défaut et un thème clair optionnel. Tout est responsive, optimisé pour le mobile, et installable sur l'écran d'accueil.",
        bullets: [
          "Design dark-first (palette bleu/cyan) avec thème clair.",
          "Mobile-first, safe areas, momentum scroll, sans flash au tap.",
          "Glassmorphism, halos lumineux, texte en dégradé.",
          "Mode compact pour densité d'information.",
          "Accessibilité : reduced-motion, contrastes lisibles.",
        ],
      },
    ],
  },
  {
    slug: 'stack',
    icon: 'Zap',
    title: "Stack technique",
    tagline: "Technologies et architecture",
    color: '#1dd8b4',
    intro: "EZA repose sur React + Vite pour le front, Tailwind CSS + shadcn/ui pour le style, et le backend-as-a-service Base44 pour les données, l'authentification, les fonctions et les intégrations.",
    sections: [
      {
        title: "Frontend",
        body: "L'interface est une SPA React construite avec Vite (ESM). Le style utilise Tailwind CSS mappé sur des tokens CSS, et shadcn/ui fournit les primitives (boutons, dialogues, selects, tabs…).",
        bullets: [
          "React 18 + Vite (ESM, pas de require).",
          "Tailwind CSS + shadcn/ui (composants dans src/components/ui).",
          "react-router-dom v6 pour le routing.",
          "@tanstack/react-query pour le data fetching et le cache.",
          "framer-motion pour les animations, lucide-react pour les icônes.",
          "react-leaflet pour les cartes, recharts pour les graphiques.",
          "react-quill pour l'éditeur riche, react-markdown pour le rendu.",
          "@hello-pangea/dnd pour le drag & drop.",
        ],
      },
      {
        title: "Backend",
        body: "Base44 fournit les entités (schémas JSON), l'authentification, les fonctions backend (handlers HTTP), les automations et les intégrations Core. Le SDK est pré-initialisé dans src/api/base44Client.js.",
        bullets: [
          "Entités : schémas JSON stockés dans base44/entities.",
          "Auth : email/password, Google OAuth, OTP, reset — géré par la plateforme.",
          "Fonctions backend : handlers dans base44/functions (entry.ts).",
          "Intégrations Core : LLM, upload, génération image/audio/vidéo, email, transcription, extraction.",
          "RLS (Row-Level Security) pour restreindre l'accès aux données.",
          "Realtime via entity.subscribe.",
        ],
      },
      {
        title: "Services externes",
        body: "L'app s'appuie sur plusieurs services externes pour les paiements, les notifications, les GIFs et l'authentification sociale.",
        bullets: [
          "Stripe — certifications, donations, abonnements, portail client.",
          "web-push (VAPID) + Firebase Cloud Messaging — notifications push.",
          "GIPHY — recherche de GIFs.",
          "Google OAuth — connexion sociale + One Tap.",
          "Outlook — synchronisation du calendrier (rendez-vous).",
        ],
      },
    ],
  },
  {
    slug: 'social',
    icon: 'Users',
    title: "Réseau social",
    tagline: "Fil, publications, likes, réponses",
    color: '#38aadc',
    intro: "Le réseau social est le cœur d'EZA. Les utilisateurs publient du contenu (texte, médias, sondages), interagissent (likes, réponses, partages) et suivent d'autres comptes.",
    sections: [
      {
        title: "Les publications",
        body: "Une publication (Post) contient du texte libre dans lequel les hashtags (#) et les mentions (@username) sont extraits automatiquement. On peut y joindre des médias (images, vidéos, GIFs) et un sondage.",
        bullets: [
          "Contenu texte avec hashtags et mentions auto-extraits.",
          "Médias multiples (images, vidéos, GIFs via GIPHY).",
          "Sondages : question, options, votes, durée, total.",
          "Auteur (snapshot : nom, username, avatar, vérifications).",
          "Visibilité : publique ou abonnés·es seulement.",
          "Épinglage possible d'une publication.",
        ],
      },
      {
        title: "Interactions",
        body: "Chaque publication expose des actions sociales : aimer, répondre, partager, signaler, éditer, supprimer.",
        bullets: [
          "Like — incrémente likes_count, ajoute l'utilisateur à liked_by.",
          "Réponse — crée un Post avec reply_to_id (thread).",
          "Partage — copie un lien de partage.",
          "Signalement — ouvre un ReportModal (entité Report).",
          "Édition / suppression — par l'auteur (RLS) ou un admin.",
          "Vues — views_count incrémenté.",
        ],
      },
      {
        title: "Hashtags & tendances",
        body: "Les hashtags alimentent la recherche et les tendances affichées dans la sidebar droite. La barre de recherche accepte aussi bien des noms d'utilisateurs que des #hashtags.",
        bullets: [
          "Extraction automatique des hashtags depuis le contenu.",
          "Sidebar tendances : hashtags les plus utilisés (Discussion + Post).",
          "Recherche par hashtag via /?tag=monTag.",
          "Recherche d'utilisateurs par nom ou @username.",
        ],
      },
      {
        title: "Suivi (Follow)",
        body: "Les utilisateurs peuvent s'abonner les uns aux autres. L'entité Follow relie un follower à un following. La sidebar propose des suggestions, et la page /discover permet d'explorer la communauté.",
        bullets: [
          "Entité Follow : follower_id / following_id.",
          "Suggestions d'utilisateurs dans la sidebar.",
          "Page /discover pour explorer.",
          "Profil public /@username avec publications et statistiques.",
        ],
      },
      {
        title: "Création de contenu",
        body: "La création d'une publication passe par un composer riche : upload de médias, recherche de GIF, créateur de sondage, autocomplétion des mentions.",
        bullets: [
          "Upload de fichiers (intégration UploadFile).",
          "GifPicker — recherche GIPHY.",
          "PollCreator — sondage avec options et durée.",
          "MentionAutocomplete — suggestion de @username.",
          "LazyMedia / VideoPlayer — chargement différé et lecture vidéo.",
        ],
      },
    ],
  },
  {
    slug: 'messaging',
    icon: 'MessageSquare',
    title: "Messagerie",
    tagline: "Conversations 1-à-1 en temps réel",
    color: '#1dd8b4',
    intro: "La messagerie permet des conversations privées entre deux utilisateurs, avec gestion des demandes de contact, modération et messages officiels de l'équipe.",
    sections: [
      {
        title: "Les conversations",
        body: "Chaque conversation est identifiée par les emails des deux participants triés alphabétiquement (emailA_emailB). Les messages stockent expéditeur, destinataire, contenu et statut de lecture.",
        bullets: [
          "Identifiant : emails triés alphabétiquement.",
          "Champs : sender_email, recipient_email, content, is_read.",
          "Statut en ligne et polling en temps réel.",
          "Marquage automatique lu + auto-scroll.",
          "Subscription temps réel pour les nouveaux messages.",
        ],
      },
      {
        title: "Demandes de contact",
        body: "Le premier message envoyé à quelqu'un est une demande de contact (is_request). Le destinataire peut l'accepter, la refuser ou l'ignorer. Tant qu'elle est en attente, elle apparaît dans le panneau des demandes.",
        bullets: [
          "is_request = true pour le premier message.",
          "request_status : pending, accepted, declined.",
          "Panneau MessageRequestsPanel pour les demandes entrantes.",
          "ConversationList + filtre demandes.",
        ],
      },
      {
        title: "Messages officiels & avertissements",
        body: "L'équipe peut envoyer des messages officiels (is_official) mis en forme distinctement, et des avertissements (is_warning). Des notes internes (is_admin_note) existent mais ne sont pas visibles côté utilisateur.",
        bullets: [
          "is_official — message de l'équipe, style dédié.",
          "is_warning — avertissement, style orange.",
          "is_admin_note — note interne, invisible pour l'utilisateur.",
        ],
      },
      {
        title: "Modération",
        body: "Chaque conversation peut être modérée via l'entité ConversationControl : verrouillage, blocage unidirectionnel, notes et raison de modération.",
        bullets: [
          "Verrouillage pour les deux participants (locked_for_all).",
          "Verrouillage unilatéral (locked_for_email).",
          "Blocage unidirectionnel (blocked_a_to_b / blocked_b_to_a).",
          "Notes de modération et raison.",
        ],
      },
      {
        title: "Raffinement par IA",
        body: "Le composer peut raffiner un message via une fonction backend (refineMessageWithAI) qui appelle un LLM pour reformuler, adoucir ou résumer le texte avant l'envoi.",
        bullets: [
          "Refactor du texte via LLM.",
          "Rendu immédiat dans le composer.",
          "L'utilisateur reste maître de l'envoi final.",
        ],
      },
    ],
  },
  {
    slug: 'forum',
    icon: 'MessagesSquare',
    title: "Forum & discussions",
    tagline: "Échanges thématiques communautaires",
    color: '#f59e0b',
    intro: "Le forum regroupe des discussions classées par catégorie. Les utilisateurs créent des sujets, y répondent, likent les réponses et marquent des solutions.",
    sections: [
      {
        title: "Les discussions",
        body: "Une Discussion a un titre, un contenu, une catégorie et un auteur (snapshot persistant). Elle expose des compteurs (réponses, vues) et la date de dernière réponse.",
        bullets: [
          "Catégories : general, technique, aide, partages, autres.",
          "Auteur (snapshot : nom, username, avatar, vérifications, badges, statut suprême).",
          "Tags libres, compteur de réponses et de vues.",
          "Épinglage (is_pinned) et verrouillage (is_locked).",
          "Sujets officiels (is_official) et annonces (is_announcement).",
        ],
      },
      {
        title: "Les réponses",
        body: "Chaque DiscussionReply contient un texte, un auteur (snapshot), un compteur de likes et la liste des likers. Une réponse peut être marquée comme solution.",
        bullets: [
          "Contenu + auteur (snapshot persistant).",
          "Likes (likes_count, liked_by).",
          "Marquage comme solution (is_solution).",
          "Rendu Markdown style Discord.",
        ],
      },
      {
        title: "Modèles de données alternatifs",
        body: "Le forum existe aussi sous forme ForumTopic / ForumPost, un modèle alternatif où l'auteur est persistant même après suppression du compte (username et email conservés).",
        bullets: [
          "ForumTopic — sujet avec catégorie, tags, vues, réponses.",
          "ForumPost — réponse avec auteur persistant (username, email, avatar).",
          "Badges de l'auteur au moment de la création.",
        ],
      },
      {
        title: "Composants",
        body: "Le forum s'appuie sur une série de composants dédiés pour la création, l'affichage et la gestion des liens externes.",
        bullets: [
          "DiscussionCard — carte de discussion.",
          "NewDiscussionDialog — création d'une discussion.",
          "DiscordMarkdown — rendu Markdown.",
          "ExternalLinkModal — gestion des liens externes.",
        ],
      },
    ],
  },
  {
    slug: 'portfolio',
    icon: 'Map',
    title: "Portfolio",
    tagline: "Projets, avant/après, avis clients",
    color: '#a78bfa',
    intro: "Le portfolio présente les projets réalisés, filtrables par catégorie, avec un détail riche (média, description, tags) et des avis clients notés en étoiles.",
    sections: [
      {
        title: "La galerie de projets",
        body: "Sur /portfolio, une galerie de cartes (Project) s'affiche avec des filtres par catégorie. Chaque carte ouvre un détail avec média, description, tags, infos client et avis.",
        bullets: [
          "Catégories : evenement, inspection, chantier, particulier, entreprise, formation.",
          "Types de média : image, youtube, tiktok, instagram, vimeo.",
          "Filtres dynamiques par catégorie.",
          "Détail : média rendu (image / embed YouTube / lien), description, tags.",
          "Projet vedette (is_featured) + ordre d'affichage.",
        ],
      },
      {
        title: "Avant / Après",
        body: "Des comparaisons avant/après (BeforeAfterGallery) s'affichent avec un slider glissable pour comparer les deux images en temps réel.",
        bullets: [
          "Catégories : inspection, immobilier, evenement, retouche, chantier.",
          "Slider glissable (BeforeAfterSlider).",
          "Labels personnalisables (avant / après).",
          "Description et ordre d'affichage.",
        ],
      },
      {
        title: "Avis clients",
        body: "Chaque projet peut recevoir des avis (Review) : note en étoiles 1 à 5, commentaire optionnel, et badge « client vérifié » quand l'avis est validé côté modération.",
        bullets: [
          "Note 1-5 en étoiles, commentaire optionnel.",
          "Snapshot auteur (nom, avatar, badges).",
          "Badge « client vérifié » (is_verified_client).",
          "Moyenne des notes affichée.",
          "Utilisateur connecté : profil pré-rempli ; invité : saisie du nom.",
        ],
      },
      {
        title: "Projets cartographiés",
        body: "Une entité MapProject permet de localiser des projets sur une carte interactive (immobilier, mariage, tourisme), avec coordonnées, miniature et ID YouTube optionnel.",
        bullets: [
          "Catégories : immobilier, mariage, tourisme.",
          "Coordonnées lat/lng + ville.",
          "Miniature + ID YouTube optionnel.",
          "Visibilité activable/désactivable (is_active).",
        ],
      },
    ],
  },
  {
    slug: 'blog',
    icon: 'FileText',
    title: "Blog & articles",
    tagline: "Actualités, conseils et techniques",
    color: '#38aadc',
    intro: "Le blog publie des articles classés par catégorie, avec un extrait, un contenu riche (HTML/Markdown), une image de couverture et un temps de lecture estimé.",
    sections: [
      {
        title: "Les articles",
        body: "Un BlogPost a un titre, un slug, un extrait, un contenu, une image de couverture, une catégorie, des tags, un auteur et un temps de lecture.",
        bullets: [
          "Catégories : actualite, conseil, technique, projet, formation.",
          "Tags libres, auteur, publié/non publié.",
          "Compteur de vues et temps de lecture en minutes.",
          "Slug pour des URLs propres.",
        ],
      },
      {
        title: "Lecture",
        body: "La liste des articles publiés est sur /blog. Un article complet s'affiche sur /blog/:id avec le contenu rendu (Markdown), l'image de couverture et les métadonnées.",
        bullets: [
          "/blog — liste filtrée aux articles publiés.",
          "/blog/:id — article complet rendu en Markdown.",
          "Image de couverture + extrait en tête de lecture.",
        ],
      },
    ],
  },
  {
    slug: 'profile',
    icon: 'User',
    title: "Profil & profils publics",
    tagline: "Identité, badges, vérifications",
    color: '#fb7185',
    intro: "Chaque utilisateur a un profil paramétrable et un profil public consultable par la communauté, affichant publications, badges, vérifications et affiliations.",
    sections: [
      {
        title: "Profil paramétrable",
        body: "Sur /profile, l'utilisateur gère son compte et ses préférences via des sections dédiées.",
        bullets: [
          "AccountSettings — nom, email, avatar, bio, username.",
          "PreferencesSettings — thème, langue, mode compact.",
          "NotificationSettings — push, email, in-app.",
          "SecurityAndPrivacy — 2FA, sessions, RGPD, suppression.",
          "MyAffiliationsTab — affiliations d'organisation.",
          "BillingTab — abonnements et factures.",
          "UsernameChanger, DangerZone, ThemeSelector.",
        ],
      },
      {
        title: "Profil public",
        body: "Le profil public (/@username) affiche l'identité, les statistiques, les publications et les actions (suivre, message). Les badges et vérifications y sont mis en avant.",
        bullets: [
          "En-tête : avatar, nom, username, vérifications.",
          "Statistiques (publications, abonnés, abonnements).",
          "Publications de l'utilisateur.",
          "Boutons suivre / message.",
          "Affichages des affiliations publiques (modale).",
        ],
      },
      {
        title: "Badges & vérifications",
        body: "Les badges (Fondateur, Pilote, VIP, Partenaire, Beta Testeur…) et les vérifications (verified, certified, official, pro) sont affichés via des composants dédiés. Le clic sur une vérification ouvre la modale d'affiliation ou navigue vers le profil.",
        bullets: [
          "VerificationMark / VerificationChip / VerificationIcons.",
          "BadgeChip / BadgeDisplay / BadgePopup.",
          "Affichage hiérarchique (badge le plus élevé d'abord).",
          "AffiliationModal au clic sur un chip d'affiliation.",
        ],
      },
    ],
  },
  {
    slug: 'certifications',
    icon: 'Award',
    title: "Certifications",
    tagline: "Demande, paiement et badges",
    color: '#f59e0b',
    intro: "Un utilisateur peut demander une certification via un questionnaire puis un paiement Stripe. Une fois approuvée, elle se traduit par un badge de vérification.",
    sections: [
      {
        title: "La demande",
        body: "L'entité CertificationRequest stocke l'email, le nom, les réponses au questionnaire, le statut et les informations de paiement.",
        bullets: [
          "Questionnaire (responses en objet JSON).",
          "Statut : pending, approved, rejected.",
          "Date de soumission.",
          "Notes admin (non visibles côté utilisateur).",
        ],
      },
      {
        title: "Le paiement",
        body: "Le paiement se fait via Stripe. Plusieurs champs stockent les IDs Stripe (session, subscription, customer) et le statut du paiement.",
        bullets: [
          "payment_status : pending, completed, failed, refunded.",
          "stripe_session_id, stripe_subscription_id, stripe_customer_id.",
          "Création du paiement via createCertificationPayment.",
          "Remboursement possible via refundCertification.",
        ],
      },
      {
        title: "Le flux utilisateur",
        body: "Le parcours complet va du questionnaire à la confirmation par email, avec une page de succès à la fin.",
        bullets: [
          "1 — Remplissage du questionnaire.",
          "2 — Paiement Stripe.",
          "3 — Emails de confirmation (envoi, paiement, certification).",
          "4 — Page de succès /certification-success.",
          "5 — Badge de vérification affiché sur le profil.",
        ],
      },
      {
        title: "Confidentialité",
        body: "Les règles RLS garantissent que seul le demandeur voit sa propre demande, et que la gestion (update/delete) est réservée à l'administration.",
        bullets: [
          "Create : seul le propriétaire (user_email).",
          "Read : propriétaire ou admin.",
          "Update / Delete : admin uniquement.",
        ],
      },
    ],
  },
  {
    slug: 'affiliations',
    icon: 'Network',
    title: "Affiliations & Écosystème",
    tagline: "Organisations et logos publics",
    color: '#1dd8b4',
    intro: "Les affiliations relient un utilisateur à une organisation. Quand l'affiliation est acceptée et publique, le logo de l'organisation apparaît sur le profil de l'utilisateur.",
    sections: [
      {
        title: "L'affiliation",
        body: "L'entité OrganizationAffiliation relie une organisation (organizationId) à un utilisateur (userId), avec un rôle, un statut et une visibilité.",
        bullets: [
          "Rôle (member par défaut).",
          "Statut : pending, accepted, rejected, removed.",
          "Visibilité : public ou private.",
          "Snapshots : nom et avatar de l'organisation.",
          "Dates : création, acceptation, suppression.",
        ],
      },
      {
        title: "Le flux",
        body: "Une organisation invite un utilisateur (ou inversement). L'utilisateur accepte ou refuse. Si l'affiliation est publique et acceptée, le logo s'affiche publiquement.",
        bullets: [
          "Invitation dans les deux sens (organisation ↔ utilisateur).",
          "Acceptation / refus par l'utilisateur.",
          "Affichage du logo si public + accepted.",
          "Modale d'affiliation au clic sur le chip.",
        ],
      },
      {
        title: "Composants",
        body: "Plusieurs composants gèrent l'affichage et la gestion des affiliations.",
        bullets: [
          "AffiliationBadges — badges sur les profils et cartes.",
          "AffiliationModal — modale de détail au clic.",
          "OrganizationAffiliationsTab — vue organisation.",
          "MyAffiliationsTab — affiliations de l'utilisateur.",
          "useOrganizationAffiliations — hook de fetch.",
        ],
      },
      {
        title: "Écosystème & Business",
        body: "La page /ecosysteme présente l'écosystème des partenaires. L'espace /business est dédié aux comptes organisation (gestion, recrutement d'affiliés, rôles).",
        bullets: [
          "/ecosysteme — présentation des partenaires.",
          "/business — espace organisation.",
          "Accès Business conditionné (businessOnly).",
        ],
      },
    ],
  },
  {
    slug: 'enor',
    icon: 'Crown',
    title: "Enor & biographie",
    tagline: "Le fondateur",
    color: '#f59e0b',
    intro: "La page /enor est une biographie dédiée au fondateur, avec son parcours, sa crédibilité et sa timeline.",
    sections: [
      {
        title: "Contenu",
        body: "La page présente une biographie narrative avec des sections chronologiques et des éléments de crédibilité.",
        bullets: [
          "Timeline du parcours.",
          "Éléments de crédibilité et de processus.",
          "Présentation narrative.",
          "Liens vers le profil public et les affiliations.",
        ],
      },
    ],
  },
  {
    slug: 'notifications',
    icon: 'Bell',
    title: "Notifications",
    tagline: "In-app, push, email",
    color: '#38aadc',
    intro: "EZA notifie ses utilisateurs via trois canaux : in-app, push web et email.",
    sections: [
      {
        title: "Notifications in-app",
        body: "L'entité Notification stocke les notifications destinées à un utilisateur, avec un type, un titre, un contenu et un lien.",
        bullets: [
          "Destinataire (user_email), titre, contenu.",
          "Types : like, reply, follow, mention, new_message, contact_request, blog, badge, appointment, etc.",
          "Lu / non lu (is_read).",
          "Lien de redirection, expéditeur (snapshot), post concerné.",
          "Page /notifications + panneau NotificationsPanel.",
        ],
      },
      {
        title: "Push web",
        body: "Les notifications push web s'appuient sur VAPID. Chaque navigateur/appareil s'abonne (PushSubscription) et reçoit des notifications même l'app fermée.",
        bullets: [
          "PushSubscription : user_email, subscription_json, device_name.",
          "Inscription côté client (savePushSubscription, usePushNotifications).",
          "Envoi côté serveur (sendWebPush, pushNotification, sendBroadcastPush).",
          "Désinscription automatique des subscriptions 404/410.",
          "Clés VAPID en secrets (public + private).",
        ],
      },
      {
        title: "Email",
        body: "L'intégration SendEmail atteint les utilisateurs enregistrés de l'app. Des fonctions dédiées gèrent chaque cas d'usage (bienvenue, vérification, confirmation, badge, donation, devis…).",
        bullets: [
          "SendEmail — utilisateurs enregistrés uniquement.",
          "sendWelcomeEmail, sendVerificationCode.",
          "sendCertificationEmail, sendCertificationConfirmation, sendCertificationPaymentConfirmation.",
          "sendBadgeAssignedEmail, sendDonationConfirmation, sendQuoteEmail.",
          "sendAnnouncementNotification, sendQuoteConfirmation, sendDeletionEmail.",
          "Limitation : pour un destinataire externe non enregistré, prévoir un autre canal.",
        ],
      },
    ],
  },
  {
    slug: 'pwa',
    icon: 'Smartphone',
    title: "PWA & installation",
    tagline: "Installable sur iOS & Android",
    color: '#1dd8b4',
    intro: "L'application est une PWA installable sur l'écran d'accueil, avec support offline partiel et mises à jour automatiques.",
    sections: [
      {
        title: "Manifeste & service worker",
        body: "Le manifeste (public/manifest.json) décrit l'app (icônes, nom, couleurs, display). Le service worker gère le cache offline et les mises à jour.",
        bullets: [
          "manifest.json — icônes, nom, couleurs, display.",
          "vite-plugin-pwa — caching, offline, mise à jour auto.",
          "Service worker enregistré en production (index.html).",
          "Rechargement automatique après mise à jour.",
          "Service worker dédié push (push-sw.js) + Firebase (firebase-messaging-sw.js).",
        ],
      },
      {
        title: "Installation",
        body: "Un composant PwaInstallPrompt invite l'utilisateur à installer l'app. Sur iOS comme sur Android, l'app s'installe depuis le même code.",
        bullets: [
          "PwaInstallPrompt — bannière/modale d'installation.",
          "Publication native iOS/Android depuis le même code.",
          "Icône sur l'écran d'accueil + splash screen.",
        ],
      },
      {
        title: "Performance mobile",
        body: "L'app est optimisée pour le mobile : safe areas, momentum scroll, suppression du tap flash, et désactivation des backdrop-filters coûteux sur petits écrans.",
        bullets: [
          "Safe areas (env(safe-area-inset-*)).",
          "-webkit-overflow-scrolling: touch, momentum scroll.",
          "Tap highlight transparent, native-press (scale au tap).",
          "backdrop-filter désactivé sur mobile (perf).",
          "touch-action: manipulation, GPU acceleration des éléments sticky.",
        ],
      },
    ],
  },
  {
    slug: 'auth',
    icon: 'Lock',
    title: "Authentification",
    tagline: "Login, register, OTP, Google",
    color: '#fb7185',
    intro: "La plateforme Base44 gère l'authentification (tokens, sessions, vérification email). L'app fournit les pages et le flux utilisateur.",
    sections: [
      {
        title: "Pages d'auth",
        body: "Quatre pages gèrent l'authentification : login, register, forgot-password, reset-password.",
        bullets: [
          "Login — email/password + Google + lien mot de passe oublié.",
          "Register — email/password/confirm + Google, puis OTP.",
          "ForgotPassword — email → resetPasswordRequest (succès générique).",
          "ResetPassword — ?token= + nouveau mot de passe.",
        ],
      },
      {
        title: "Flux",
        body: "Le flux d'inscription impose la vérification OTP : un utilisateur non vérifié n'obtient pas de session valide.",
        bullets: [
          "Login — loginViaEmailPassword → hard redirect (gère returnTo).",
          "Register — register (non connecté, non vérifié) → OTP → verifyOtp → setToken → redirect.",
          "Google — loginWithProvider('google', fromUrl) + One Tap.",
          "Reset — resetPasswordRequest → email → resetPassword → redirect login.",
        ],
      },
      {
        title: "Protections",
        body: "Les routes authentifiées sont protégées par ProtectedRoute. Les routes publiques sont accessibles sans session.",
        bullets: [
          "ProtectedRoute — layout route protégeant les pages authentifiées.",
          "Routes publiques autorisées sans session (accueil, blog, portfolio, forum…).",
          "AuthContext — isLoadingAuth, authError (user_not_registered, auth_required).",
        ],
      },
      {
        title: "2FA & sessions",
        body: "L'utilisateur peut activer la 2FA (TOTP), gérer ses sessions d'appareils et demander la suppression de son compte.",
        bullets: [
          "TwoFactorSetup — setup TOTP (setupTOTP).",
          "verifyLoginCode / verifyEmailCode — vérification des codes.",
          "ActiveDevices / DeviceSession — sessions actives, révocation.",
          "useRegisterDevice — enregistrement de l'appareil.",
          "requestAccountDeletion + DeletionRequest.",
        ],
      },
    ],
  },
  {
    slug: 'data',
    icon: 'Database',
    title: "Modèle de données",
    tagline: "Entités, relations, RLS",
    color: '#38aadc',
    intro: "Les données sont stockées dans des entités (schémas JSON). Chaque entité hérite des attributs id, created_date, updated_date, created_by_id.",
    sections: [
      {
        title: "Entités sociales",
        body: "Le réseau social et la messagerie s'appuient sur plusieurs entités liées.",
        bullets: [
          "Post — publication (texte, médias, sondages, likes, réponses).",
          "Discussion / DiscussionReply — forum.",
          "ForumTopic / ForumPost — modèle forum alternatif (auteur persistant).",
          "Follow — relation de suivi.",
          "ChatMessage — message de messagerie 1-à-1.",
          "ConversationControl — modération.",
          "Notification — notification in-app.",
          "Block — blocage d'utilisateur.",
        ],
      },
      {
        title: "Entités portfolio",
        body: "Le portfolio utilise des entités dédiées aux projets, à la carte et aux avis.",
        bullets: [
          "Project — projet du portfolio.",
          "MapProject — projet localisé.",
          "BeforeAfterGallery — comparaison avant/après.",
          "Review — avis client sur un projet.",
        ],
      },
      {
        title: "Entités business & contenu",
        body: "Côté prestation et contenu, plusieurs entités structurent les devis, rendez-vous, articles et annonces.",
        bullets: [
          "Quote — demande de devis.",
          "Appointment — rendez-vous (lié à un devis).",
          "BlockedDay — jour bloqué (indisponible / incertain).",
          "Service, BusinessHours, ClientFile, RoofCheckup.",
          "BlogPost, Announcement, AppUpdate.",
        ],
      },
      {
        title: "Entités communauté & système",
        body: "Certifications, affiliations, parrainages et donations côté communauté ; paramètres et logs côté système.",
        bullets: [
          "CertificationRequest, OrganizationAffiliation, Referral, Donation.",
          "User (built-in), AppSettings, AppModuleStatus.",
          "PushSubscription, DeviceSession, DeletedUsername.",
          "MonitoringLog, AuditLog.",
        ],
      },
      {
        title: "Sécurité par ligne (RLS)",
        body: "Plusieurs entités appliquent des règles RLS pour restreindre qui peut lire, créer, modifier ou supprimer.",
        bullets: [
          "Post — update/delete : auteur ou admin.",
          "Review — create : auteur ou admin ; read ouvert.",
          "CertificationRequest — create : propriétaire ; read : propriétaire ou admin.",
          "OrganizationAffiliation — parties concernées ou statut accepted (read).",
          "Project — read public ; create/update/delete : admin.",
          "User — built-in (admins gèrent les autres utilisateurs).",
        ],
      },
    ],
  },
  {
    slug: 'design',
    icon: 'Palette',
    title: "Système de design",
    tagline: "Couleurs, polices, utilitaires",
    color: '#a78bfa',
    intro: "Le design s'appuie sur des tokens CSS (HSL) mappés dans Tailwind, un thème dark par défaut et un thème clair, et des polices Space Grotesk / Inter / JetBrains Mono.",
    sections: [
      {
        title: "Tokens de couleur",
        body: "Les couleurs sont définies en HSL dans index.css (root + .light) et mappées dans tailwind.config.js. On utilise les classes générées (bg-primary, text-muted-foreground…), jamais de valeurs hardcoded.",
        bullets: [
          "Thème Dark Sky — background 214 50% 4%, primary 205 90% 58%, accent 195 80% 50%.",
          "Thème light — background 210 30% 97%, primary 205 85% 40%.",
          "Charts (--chart-1 à 5) et sidebar (--sidebar-*).",
          "Destructive, border, input, ring, muted, card, popover.",
        ],
      },
      {
        title: "Polices",
        body: "Trois polices définies par des tokens et chargées depuis Google Fonts.",
        bullets: [
          "--font-grotesk — Space Grotesk (titres/display).",
          "--font-inter — Inter (corps de texte).",
          "--font-mono — JetBrains Mono (mono).",
          "Import Google Fonts en haut de index.css avant @tailwind base.",
        ],
      },
      {
        title: "Utilitaires CSS",
        body: "Des classes utilitaires custom enrichissent le design : glassmorphism, halos, dégradés, animations.",
        bullets: [
          "glass / glass-card — glassmorphism (blur + transparence).",
          "sky-glow / sky-glow-text — halos lumineux.",
          "gradient-text — texte en dégradé bleu→cyan.",
          "grid-bg — fond en grille (style drone).",
          "scan-line / pulse-ring — animations opacity-only (GPU).",
          "skeleton-shimmer — shimmer des squelettes de chargement.",
          "badge-founder — badge fondateur animé.",
          "hover-lift, compact-mode, video-overlay.",
        ],
      },
      {
        title: "Composants UI",
        body: "shadcn/ui fournit les primitives. Des composants custom gèrent l'identité (vérifications, badges, affiliations) et les uploads.",
        bullets: [
          "Primitives shadcn — button, input, dialog, select, tabs, switch, etc.",
          "VerificationIcon / VerificationMark / VerificationChip — badges de vérification.",
          "BadgeChip / BadgePopup — badges d'utilisateur.",
          "AffiliationModal — modale d'affiliation.",
          "ImageUploadOrUrl — upload fichier ou URL.",
          "Shimmer, StatusBadge, BeforeAfterSlider.",
        ],
      },
    ],
  },
  {
    slug: 'integrations',
    icon: 'Zap',
    title: "Intégrations & services",
    tagline: "LLM, Stripe, push, OAuth",
    color: '#1dd8b4',
    intro: "L'app s'appuie sur les intégrations Core de Base44, des connecteurs OAuth, Stripe et des services externes.",
    sections: [
      {
        title: "Intégrations Core",
        body: "Les intégrations built-in couvrent l'IA, les fichiers, la génération de média et l'email.",
        bullets: [
          "InvokeLLM — appel LLM (prompt, JSON schema, fichiers, contexte internet).",
          "UploadFile / UploadPrivateFile — uploads public/privé + CreateFileSignedUrl.",
          "GenerateImage — génération d'image IA.",
          "GenerateSpeech — TTS (voix : river, honey, sunny, storm, spark).",
          "GenerateVideo — génération vidéo IA (Veo).",
          "TranscribeAudio — transcription audio (Whisper).",
          "ExtractDataFromUploadedFile — extraction structurée.",
          "SendEmail — email aux utilisateurs enregistrés.",
        ],
      },
      {
        title: "Paiements Stripe",
        body: "Stripe gère les certifications, donations, abonnements et le portail client.",
        bullets: [
          "createCertificationPayment — paiement de certification.",
          "createDonationPayment — paiement de don.",
          "handleStripeWebhook — webhooks Stripe.",
          "getMySubscriptions / cancelSubscription — abonnements.",
          "createBillingPortal / getStripePortalUrl — portail client.",
          "refundCertification — remboursement.",
          "syncStripeDonations — synchronisation des dons.",
        ],
      },
      {
        title: "Notifications push",
        body: "Les notifications push utilisent VAPID côté web et Firebase côté mobile.",
        bullets: [
          "web-push (VAPID) — sendWebPush, pushNotification, sendBroadcastPush.",
          "savePushSubscription — inscription côté client.",
          "Firebase Cloud Messaging (FCM_SERVER_KEY) — push mobile.",
          "generateVapidKeys — génération des clés VAPID.",
        ],
      },
      {
        title: "OAuth & autres services",
        body: "Connecteurs OAuth et services externes variés.",
        bullets: [
          "Google OAuth — login social + One Tap (googleOneTapAuth).",
          "Outlook — sync calendrier (syncAppointmentToOutlook, deleteOutlookAppointment).",
          "GIPHY (GIPHY_API_KEY) — recherche de GIFs (searchGifs).",
          "Scores de football — getFootballScores.",
          "Monitoring — runMonitoring, statusCheck.",
        ],
      },
    ],
  },
  {
    slug: 'security',
    icon: 'Shield',
    title: "Sécurité & confidentialité",
    tagline: "RGPD, 2FA, modération",
    color: '#fb7185',
    intro: "Côté utilisateur, EZA met l'accent sur le contrôle des données personnelles, la 2FA, la gestion des sessions et la modération.",
    sections: [
      {
        title: "Données personnelles",
        body: "L'utilisateur peut demander la suppression de son compte. Son username est réservé 30 jours après suppression.",
        bullets: [
          "Page /account-deletion — demande de suppression.",
          "DeletionRequest + requestAccountDeletion.",
          "Username réservé 30 jours (DeletedUsername).",
          "Refus possible (refuseDeletionRequest).",
        ],
      },
      {
        title: "2FA & sessions",
        body: "L'authentification à deux facteurs (TOTP) et la gestion des sessions d'appareils renforcent la sécurité.",
        bullets: [
          "TwoFactorSetup — setup TOTP (setupTOTP).",
          "verifyLoginCode / verifyEmailCode — vérification des codes.",
          "DeviceSession — sessions d'appareils actives.",
          "createDeviceSession / deleteDeviceSession.",
          "SecurityAndPrivacy — panneau de gestion.",
        ],
      },
      {
        title: "RGPD",
        body: "Un tableau de bord RGPD et des pages légales informent l'utilisateur.",
        bullets: [
          "RGPDDashboard — tableau de bord RGPD.",
          "/legal/privacy — politique de confidentialité.",
          "/legal/terms — conditions générales d'utilisation.",
          "/legal/cookies — politique cookies.",
          "CookieBanner — bannière de consentement.",
        ],
      },
      {
        title: "Modération",
        body: "La communauté est modérée via les signalements, les blocages et la modération des conversations.",
        bullets: [
          "Report — signalements via ReportModal.",
          "Block — blocage d'utilisateurs.",
          "ConversationControl — modération des conversations.",
          "Messages officiels et avertissements.",
        ],
      },
      {
        title: "Push notifications",
        body: "L'inscription push nécessite un consentement explicite. Les subscriptions invalides (404/410) sont automatiquement supprimées.",
        bullets: [
          "Consentement explicite avant inscription push.",
          "Désinscription automatique des subscriptions 404/410.",
          "Paramètres de notifications par canal.",
        ],
      },
    ],
  },
  {
    slug: 'conventions',
    icon: 'Code2',
    title: "Conventions de code",
    tagline: "Standards de développement",
    color: '#38aadc',
    intro: "Le code suit des conventions strictes pour garantir la cohérence et la fiabilité.",
    sections: [
      {
        title: "Imports & modules",
        body: "L'app est ESM uniquement. Les imports utilisent l'alias @/.",
        bullets: [
          "ESM uniquement — pas de require() / module.exports.",
          "Alias @/ (jamais de chemins relatifs src/).",
          "cn depuis @/lib/utils, createPageUrl depuis @/utils.",
          "shadcn — chaque primitive depuis son propre fichier.",
          "Icônes lucide-react uniquement, alias si collision de nom.",
        ],
      },
      {
        title: "Composants",
        body: "Les composants sont petits et focalisés.",
        bullets: [
          "Fichiers ≤ 50 lignes, un composant par fichier.",
          "Export default nommé comme le fichier.",
          "Hooks au top-level, jamais conditionnellement.",
          "JSX uniquement en .jsx/.tsx.",
        ],
      },
      {
        title: "Style & tokens",
        body: "On utilise les classes mappées sur les tokens, jamais de valeurs hardcoded.",
        bullets: [
          "Classes Tailwind en chaînes littérales (le purge supprime le dynamique).",
          "Tokens via classes (bg-primary, font-heading), pas de bg-[#fff].",
          "safelist uniquement pour valeurs runtime (entités, API, input).",
        ],
      },
      {
        title: "Erreurs & analytics",
        body: "Les erreurs remontent par défaut, sauf les flows utilisateur qui catchent et affichent inline. Les events analytics sont nommés clairement sans PII.",
        bullets: [
          "Erreurs laissées remonter (sauf form/auth).",
          "base44.analytics.track — eventName + propriétés minimales.",
          "Pas de PII dans les events analytics.",
        ],
      },
    ],
  },
];

export const getDocTopic = (slug) => DOC_TOPICS.find(t => t.slug === slug);