/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        grotesk: ['var(--font-grotesk)'],
        inter: ['var(--font-inter)'],
        mono: ['var(--font-mono)'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        sky: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        float: 'float 6s ease-in-out infinite',
        'fade-up': 'fade-up 0.6s ease-out forwards',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'text-primary', 'text-accent', 'text-chart-5', 'text-destructive', 'text-muted-foreground',
    'text-green-400', 'text-blue-400', 'text-blue-300', 'text-cyan-400', 'text-orange-400', 'text-purple-400',
    'text-yellow-400', 'text-amber-300', 'text-slate-300', 'text-slate-400', 'text-red-400', 'text-red-500',
    'text-pink-400', 'text-teal-400', 'text-indigo-400', 'text-violet-400',
    'bg-primary/5', 'bg-primary/10', 'bg-accent/10', 'bg-chart-5/10', 'bg-destructive/10',
    'bg-green-400/5', 'bg-green-400/10', 'bg-blue-400/5', 'bg-blue-400/10', 'bg-blue-300/5',
    'bg-cyan-400/5', 'bg-cyan-400/10', 'bg-orange-400/5', 'bg-orange-400/10', 'bg-purple-400/5', 'bg-purple-400/10',
    'bg-yellow-400/5', 'bg-yellow-400/10', 'bg-amber-300/5', 'bg-slate-300/5', 'bg-slate-400/5',
    'bg-red-400/5', 'bg-red-500/8', 'bg-pink-400/5', 'bg-teal-400/5', 'bg-indigo-400/5', 'bg-violet-400/5',
    'border-primary/30', 'border-accent/30', 'border-chart-5/30', 'border-destructive/30',
    'border-green-400/30', 'border-green-400/40', 'border-blue-400/30', 'border-blue-400/40', 'border-blue-300/30',
    'border-cyan-400/30', 'border-cyan-400/40', 'border-orange-400/30', 'border-orange-400/40',
    'border-purple-400/30', 'border-purple-400/40', 'border-yellow-400/30', 'border-amber-300/30',
    'border-slate-300/30', 'border-slate-400/30', 'border-red-400/30', 'border-red-500/40',
    'border-pink-400/30', 'border-teal-400/30', 'border-indigo-400/30', 'border-violet-400/30',
    'bg-yellow-400', 'bg-amber-300', 'bg-slate-300', 'bg-slate-400', 'bg-red-400', 'bg-red-500',
    'bg-cyan-400', 'bg-pink-400', 'bg-teal-400', 'bg-indigo-400', 'bg-violet-400',
  ],
}