import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, Eye, EyeOff, Loader2, Lock } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Input } from '@/components/ui/input';
import AuthBrandPanel from '@/components/auth/AuthBrandPanel';

export default function ResetPassword() {
  const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  const resetToken = new URLSearchParams(window.location.search).get('token');
  const submit = async event => { event.preventDefault(); setError(''); if (!resetToken) return setError('Ce lien de réinitialisation est invalide.'); if (password !== confirmPassword) return setError('Les mots de passe ne correspondent pas.'); setLoading(true); try { await base44.auth.resetPassword({ resetToken, newPassword: password }); window.location.href = '/login'; } catch { setError('Ce lien est invalide ou a expiré.'); } finally { setLoading(false); } };
  return <div className="flex min-h-screen bg-background"><AuthBrandPanel /><main className="flex flex-1 items-center justify-center px-6 py-12"><div className="w-full max-w-md">{done ? <><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-green-400/10"><CheckCircle2 className="h-7 w-7 text-green-400" /></span><h1 className="mt-6 font-grotesk text-3xl font-black">Mot de passe mis à jour</h1><p className="mt-3 font-inter text-sm text-muted-foreground">Vous pouvez maintenant vous connecter à votre compte eza.</p><Link to="/login" className="mt-8 inline-block rounded-xl bg-primary px-5 py-3 font-inter text-sm font-bold text-primary-foreground">Se connecter</Link></> : <><h1 className="font-grotesk text-3xl font-black">Créer un nouveau mot de passe</h1><p className="mt-2 font-inter text-sm text-muted-foreground">Choisissez un mot de passe sécurisé pour votre compte eza.</p><form onSubmit={submit} className="mt-8 space-y-4"><PasswordField label="Nouveau mot de passe" value={password} onChange={setPassword} show={showPassword} toggle={() => setShowPassword(!showPassword)} /><PasswordField label="Confirmer le mot de passe" value={confirmPassword} onChange={setConfirmPassword} />{error && <p className="rounded-xl border border-destructive/30 bg-destructive/10 px-3 py-2.5 text-xs text-destructive">{error}</p>}<button disabled={loading} className="flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary font-inter text-sm font-bold text-primary-foreground disabled:opacity-60">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Enregistrer le nouveau mot de passe'}</button></form></>}</div></main></div>;
}
function PasswordField({ label, value, onChange, show, toggle }) { return <label className="block"><span className="mb-1.5 block font-inter text-xs font-semibold">{label}</span><span className="relative block"><Lock className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><Input type={show ? 'text' : 'password'} value={value} onChange={e => onChange(e.target.value)} className="h-11 pl-9 pr-10" minLength={6} required />{toggle && <button type="button" onClick={toggle} className="absolute right-3 top-3 text-muted-foreground">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button>}</span></label>; }